name: WorldPortals
main: cl.netgamer.worldportals.Main
version: 5

commands:
   portal:
      description: 'Builds world portals (help: /p)'
      aliases: [p]
   listportals:
      description: 'Lists world portals (help: /lp ?)'
      aliases: [lp]

# v4 - add select portals that points to 'pattern?' list option 
# v3 - "portallist" command renamed to "listportals" with alias "lp" due alias conflict
# v2 - add pl alias
 